search_data:
  - file: "/etc/systemd/system/keycloak.service.d/99-custom.conf"
    string: "JAVA_OPTS"
    suggestion: "[Service] \n Environment=\"JAVA_OPTS=-Xms128m -Xmx1024m\""
#  - file: "/etc/systemd/system/elasticrvice.d/99-custom.conf"
#    string: "JAVA_OPTS"
#    suggestion: "[Service] \n Environment=\"JAVA_OPTS=-Xms128m -Xmx1024m\""
