{
 "title": "Overview AX BATCH JOB",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "SISTEMA", "query": "influxdb" },
   {
    "name": "DBname",
    "label": "AX Env DB name",
    "query": "show tag values from  AXBatchSessionOverviewByAOS with key=DBName"
   },
   {
    "name": "AOSBATCHSERVERS_FIXED",
    "query": "de-ffm-s-aos217,de-ffm-s-aos218,de-ffm-s-aos223,de-ffm-s-aos224"
   },
   {
    "name": "AOSBATCHSERVERSQry",
    "label": "AX Env DB name",
    "query": "show tag values from  AXBatchSessionOverviewByAOS with key=host where DBName=~ /^$DBname$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Overdue Batch Tasks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT mean(\"cntBatchOverdue\") AS \"Overdue\" FROM \"AXBatchOverdueByGrp\" WHERE (\"DBName\" =~ /(?i)^$DBname$/) AND $timeFilter GROUP BY time(1m), \"GROUPID\" fill(null)"
    }
   ]
  },
  {
   "title": "AX Running BATCH Sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "AOSServer" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "AXBatchSessionOverviewByAOS",
     "query": "SELECT max(\"runningBatchSessions\") AS \"Running\" FROM \"AXBatchSessionOverviewByAOS\" WHERE (\"DBName\" =~ /(?i)^$DBname$/) AND $timeFilter GROUP BY time($__interval), \"AOSServer\" fill(none)",
     "select": [
      [
       { "params": [ "runningBatchSessions" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Running" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "DBName", "operator": "=~", "value": "/^$DBname$/" }
     ]
    }
   ]
  },
  {
   "title": "AX Free BATCH Sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "AOSServer" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "AXBatchSessionOverviewByAOS",
     "query": "SELECT mean(\"freeBatchSessions\") AS \"Free\" FROM \"AXBatchSessionOverviewByAOS\" WHERE (\"DBName\" =~ /(?i)^$DBname$/) AND $timeFilter GROUP BY time($interval), \"AOSServer\" fill(none)",
     "select": [
      [
       { "params": [ "freeBatchSessions" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "DBName", "operator": "=~", "value": "/^$DBname$/" }
     ]
    }
   ]
  },
  {
   "title": "BATCH AOS Processor Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Processor",
     "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"Processor\" WHERE (\"host\" =~ /(?i)^$AOSBATCHSERVERS$/ OR \"host\" =~ /(?i)^$AOSBATCHSERVERSQry$/) AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$AOSBATCHSERVERS$/" },
      { "condition": "OR", "key": "host", "operator": "=~", "value": "/^$AOSBATCHSERVERSQry$/" }
     ]
    }
   ]
  },
  {
   "title": "BATCH AOS available Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Memory",
     "query": "SELECT mean(\"Available_KBytes\") FROM \"Memory\" WHERE (\"host\" =~ /(?i)^$AOSBATCHSERVERS$/ OR \"host\" =~ /(?i)^$AOSBATCHSERVERSQry$/) AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "Available_KBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$AOSBATCHSERVERS$/" },
      { "condition": "OR", "key": "host", "operator": "=~", "value": "/^$AOSBATCHSERVERSQry$/" }
     ]
    }
   ]
  }
 ]
}