{
 "title": "SQLXEview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "SISTEMA", "query": "influxdb" },
   {
    "name": "SQLNODE",
    "query": "SHOW TAG VALUES FROM \"sqlXeEvents\" WITH KEY = \"host\""
   },
   {
    "name": "SQLINSTANCE",
    "query": "SHOW TAG VALUES FROM \"sqlXeEvents\" WITH KEY = \"SQLInstance\"  where \"host\" =~ /^$SQLNODE$/"
   },
   { "name": "AGGR_INTERVAL", "query": "1m,2m,3m,5m,10m,15m,30m,1h" },
   {
    "name": "USER",
    "query": "SHOW TAG VALUES FROM \"sqlXeEvents\" WITH KEY = \"AxUser\" where \"host\" =~ /^$SQLNODE$/ and \"SQLInstance\" =~/^$SQLINSTANCE$/"
   },
   {
    "name": "SQLUSER",
    "query": "SHOW TAG VALUES FROM \"sqlXeEvents\" WITH KEY = \"SqlUser\" where \"host\" =~ /^$SQLNODE$/ and \"SQLInstance\" =~/^$SQLINSTANCE$/"
   },
   {
    "name": "SESSION",
    "query": "SHOW TAG VALUES FROM \"sqlXeEvents\" WITH KEY = \"AxSession\" where \"host\" =~ /^$SQLNODE$/ and \"SQLInstance\" =~/^$SQLINSTANCE$/"
   },
   {
    "name": "CLIENTHOST",
    "query": "SHOW TAG VALUES FROM \"sqlXeEvents\" WITH KEY = \"SqlHostName\" where \"host\" =~ /^$SQLNODE$/ and \"SQLInstance\" =~/^$SQLINSTANCE$/"
   },
   {
    "name": "DBNAME",
    "query": "SHOW TAG VALUES FROM \"sqlXeEvents\" WITH KEY = \"DatabaseName\" where \"host\" =~ /^$SQLNODE$/ and \"SQLInstance\" =~/^$SQLINSTANCE$/"
   },
   {
    "name": "sqleventname",
    "label": "SQLEVENTNAME",
    "query": "rpc_completed, sp_statement_completed, sql_statement_completed"
   },
   {
    "name": "QueryHash",
    "label": "QUERYHASH",
    "query": "SHOW TAG VALUES FROM \"sqlXeEvents\" WITH KEY = \"SqlQueryHash\" where \"host\" =~ /^$SQLNODE$/ and \"SQLInstance\" =~/^$SQLINSTANCE$/"
   },
   {
    "name": "FetchesQueryHash",
    "label": "FETCHES QUERYHASH",
    "query": "SHOW TAG VALUES FROM \"sqlXeFetches\" WITH KEY = \"query_hash\" where \"host\" =~ /^$SQLNODE$/ and \"SQLInstance\" =~/^$SQLINSTANCE$/"
   }
  ]
 },
 "panels": [
  {
   "title": "TOTALS ${SQLINSTANCE}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "SQLINSTANCE",
   "collapsed": true,
   "panels": [
    {
     "title": "SqlXe - physicalReads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "SqlEventName" ], "type": "tag" }
       ],
       "measurement": "sqlXeEvents",
       "query": "SELECT sum(\"physical_reads\") *8 FROM \"queryhashcodemetrics\".\"sqlXeEvents\" WHERE (\"AxUser\" =~ /^$USER$/ AND \"SqlHostName\" =~ /(?i)^$CLIENTHOST$/ AND \"SqlEventName\" =~ /^$sqleventname$/ AND \"SQLInstance\" =~ /(?i)^$SQLINSTANCE$/ AND \"SqlUser\" =~ /^$SQLUSER$/) AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"SqlEventName\"",
       "select": [
        [
         { "params": [ "physical_reads" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "*8" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "SqlHostName", "operator": "=~", "value": "/^$CLIENTHOST$/" },
        { "condition": "AND", "key": "SqlEventName", "operator": "=~", "value": "/^$sqleventname$/" },
        { "condition": "AND", "key": "SQLInstance", "operator": "=~", "value": "/^$SQLINSTANCE$/" },
        { "condition": "AND", "key": "SqlUser", "operator": "=~", "value": "/^$SQLUSER$/" }
       ]
      }
     ]
    },
    {
     "title": "SqlXe -logicalReads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "SqlEventName" ], "type": "tag" }
       ],
       "measurement": "sqlXeEvents",
       "query": "SELECT sum(\"logical_reads\") *8 FROM \"queryhashcodemetrics\".\"sqlXeEvents\" WHERE (\"AxUser\" =~ /^$USER$/ AND \"SqlHostName\" =~ /(?i)^$CLIENTHOST$/ AND \"SqlEventName\" =~ /^$sqleventname$/ AND \"SQLInstance\" =~ /(?i)^$SQLINSTANCE$/ AND \"SqlUser\" =~ /^$SQLUSER$/) AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"SqlEventName\"",
       "select": [
        [
         { "params": [ "logical_reads" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "*8" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "SqlHostName", "operator": "=~", "value": "/^$CLIENTHOST$/" },
        { "condition": "AND", "key": "SqlEventName", "operator": "=~", "value": "/^$sqleventname$/" },
        { "condition": "AND", "key": "SQLInstance", "operator": "=~", "value": "/^$SQLINSTANCE$/" },
        { "condition": "AND", "key": "SqlUser", "operator": "=~", "value": "/^$SQLUSER$/" }
       ]
      }
     ]
    },
    {
     "title": "SqlXe - writes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "SqlEventName" ], "type": "tag" }
       ],
       "measurement": "sqlXeEvents",
       "query": "SELECT sum(\"writes\") *8 FROM \"queryhashcodemetrics\".\"sqlXeEvents\" WHERE (\"AxUser\" =~ /^$USER$/ AND \"SqlHostName\" =~ /(?i)^$CLIENTHOST$/ AND \"SqlEventName\" =~ /^$sqleventname$/ AND \"SQLInstance\" =~ /(?i)^$SQLINSTANCE$/ AND \"SqlUser\" =~ /^$SQLUSER$/) AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"SqlEventName\"",
       "select": [
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "*8" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "SqlHostName", "operator": "=~", "value": "/^$CLIENTHOST$/" },
        { "condition": "AND", "key": "SqlEventName", "operator": "=~", "value": "/^$sqleventname$/" },
        { "condition": "AND", "key": "SQLInstance", "operator": "=~", "value": "/^$SQLINSTANCE$/" },
        { "condition": "AND", "key": "SqlUser", "operator": "=~", "value": "/^$SQLUSER$/" }
       ]
      }
     ]
    },
    {
     "title": "SqlXe -cpu_time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "SqlEventName" ], "type": "tag" }
       ],
       "measurement": "sqlXeEvents",
       "query": "SELECT sum(\"cpu_time\") FROM \"queryhashcodemetrics\".\"sqlXeEvents\" WHERE (\"AxUser\" =~ /^$USER$/ AND \"SqlHostName\" =~ /(?i)^$CLIENTHOST$/ AND \"SqlEventName\" =~ /^$sqleventname$/ AND \"SQLInstance\" =~ /(?i)^$SQLINSTANCE$/ AND \"SqlUser\" =~ /^$SQLUSER$/) AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"SqlEventName\"",
       "select": [
        [
         { "params": [ "cpu_time" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "SqlHostName", "operator": "=~", "value": "/^$CLIENTHOST$/" },
        { "condition": "AND", "key": "SqlEventName", "operator": "=~", "value": "/^$sqleventname$/" },
        { "condition": "AND", "key": "SQLInstance", "operator": "=~", "value": "/^$SQLINSTANCE$/" },
        { "condition": "AND", "key": "SqlUser", "operator": "=~", "value": "/^$SQLUSER$/" }
       ]
      }
     ]
    },
    {
     "title": "SqlXe -duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "SqlEventName" ], "type": "tag" }
       ],
       "measurement": "sqlXeEvents",
       "query": "SELECT sum(\"duration\") FROM \"queryhashcodemetrics\".\"sqlXeEvents\" WHERE (\"AxUser\" =~ /^$USER$/ AND \"SqlHostName\" =~ /(?i)^$CLIENTHOST$/ AND \"SqlEventName\" =~ /^$sqleventname$/ AND \"SQLInstance\" =~ /(?i)^$SQLINSTANCE$/ AND \"SqlUser\" =~ /^$SQLUSER$/) AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"SqlEventName\"",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "SqlHostName", "operator": "=~", "value": "/^$CLIENTHOST$/" },
        { "condition": "AND", "key": "SqlEventName", "operator": "=~", "value": "/^$sqleventname$/" },
        { "condition": "AND", "key": "SQLInstance", "operator": "=~", "value": "/^$SQLINSTANCE$/" },
        { "condition": "AND", "key": "SqlUser", "operator": "=~", "value": "/^$SQLUSER$/" }
       ]
      }
     ]
    },
    {
     "title": "SqlXe -count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "SqlEventName" ], "type": "tag" }
       ],
       "measurement": "sqlXeEvents",
       "query": "SELECT count(\"duration\") FROM \"queryhashcodemetrics\".\"sqlXeEvents\" WHERE (\"AxUser\" =~ /^$USER$/ AND \"SqlHostName\" =~ /(?i)^$CLIENTHOST$/ AND \"SqlEventName\" =~ /^$sqleventname$/ AND \"SQLInstance\" =~ /(?i)^$SQLINSTANCE$/ AND \"SqlUser\" =~ /^$SQLUSER$/) AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"SqlEventName\"",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "SqlHostName", "operator": "=~", "value": "/^$CLIENTHOST$/" },
        { "condition": "AND", "key": "SqlEventName", "operator": "=~", "value": "/^$sqleventname$/" },
        { "condition": "AND", "key": "SQLInstance", "operator": "=~", "value": "/^$SQLINSTANCE$/" },
        { "condition": "AND", "key": "SqlUser", "operator": "=~", "value": "/^$SQLUSER$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "QUERY_HASH ${SQLINSTANCE}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "SQLINSTANCE",
   "collapsed": true,
   "panels": [
    {
     "title": "SqlXe -Query CPU Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "SqlQueryHash" ], "type": "tag" }
       ],
       "measurement": "sqlXeEvents",
       "query": "SELECT sum(\"cpu_time\") FROM \"queryhashcodemetrics\".\"sqlXeEvents\" WHERE (\"AxUser\" =~ /^$USER$/ AND \"SqlHostName\" =~ /(?i)^$CLIENTHOST$/ AND \"SqlEventName\" =~ /^$sqleventname$/ AND \"SQLInstance\" =~ /(?i)^$SQLINSTANCE$/ AND \"SqlQueryHash\" =~ /^$QueryHash$/ AND \"AxSession\" =~ /^$SESSION$/ AND \"SqlUser\" =~ /^$SQLUSER$/) AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"SqlQueryHash\"",
       "select": [
        [
         { "params": [ "cpu_time" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "SqlHostName", "operator": "=~", "value": "/^$CLIENTHOST$/" },
        { "condition": "AND", "key": "SqlEventName", "operator": "=~", "value": "/^$sqleventname$/" },
        { "condition": "AND", "key": "SQLInstance", "operator": "=~", "value": "/^$SQLINSTANCE$/" },
        { "condition": "AND", "key": "SqlQueryHash", "operator": "=~", "value": "/^$QueryHash$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" },
        { "condition": "AND", "key": "SqlUser", "operator": "=~", "value": "/^$SQLUSER$/" }
       ]
      }
     ]
    },
    {
     "title": "SqlXe -Query duration Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "SqlQueryHash" ], "type": "tag" }
       ],
       "measurement": "sqlXeEvents",
       "query": "SELECT sum(\"duration\") FROM \"queryhashcodemetrics\".\"sqlXeEvents\" WHERE (\"AxUser\" =~ /^$USER$/ AND \"SqlHostName\" =~ /(?i)^$CLIENTHOST$/ AND \"SqlEventName\" =~ /^$sqleventname$/ AND \"SQLInstance\" =~ /(?i)^$SQLINSTANCE$/ AND \"SqlQueryHash\" =~ /^$QueryHash$/ AND \"AxSession\" =~ /^$SESSION$/ AND \"SqlUser\" =~ /^$SQLUSER$/) AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"SqlQueryHash\"",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "SqlHostName", "operator": "=~", "value": "/^$CLIENTHOST$/" },
        { "condition": "AND", "key": "SqlEventName", "operator": "=~", "value": "/^$sqleventname$/" },
        { "condition": "AND", "key": "SQLInstance", "operator": "=~", "value": "/^$SQLINSTANCE$/" },
        { "condition": "AND", "key": "SqlQueryHash", "operator": "=~", "value": "/^$QueryHash$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" },
        { "condition": "AND", "key": "SqlUser", "operator": "=~", "value": "/^$SQLUSER$/" }
       ]
      }
     ]
    },
    {
     "title": "SqlXe -Query phy read",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "SqlQueryHash" ], "type": "tag" }
       ],
       "measurement": "sqlXeEvents",
       "query": "SELECT sum(\"physical_reads\") *8 FROM \"queryhashcodemetrics\".\"sqlXeEvents\" WHERE (\"AxUser\" =~ /^$USER$/ AND \"SqlHostName\" =~ /(?i)^$CLIENTHOST$/ AND \"SqlEventName\" =~ /^$sqleventname$/ AND \"SQLInstance\" =~ /(?i)^$SQLINSTANCE$/ AND \"SqlQueryHash\" =~ /^$QueryHash$/ AND \"AxSession\" =~ /^$SESSION$/ AND \"SqlUser\" =~ /^$SQLUSER$/) AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"SqlQueryHash\"",
       "select": [
        [
         { "params": [ "physical_reads" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "*8" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "SqlHostName", "operator": "=~", "value": "/^$CLIENTHOST$/" },
        { "condition": "AND", "key": "SqlEventName", "operator": "=~", "value": "/^$sqleventname$/" },
        { "condition": "AND", "key": "SQLInstance", "operator": "=~", "value": "/^$SQLINSTANCE$/" },
        { "condition": "AND", "key": "SqlQueryHash", "operator": "=~", "value": "/^$QueryHash$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" },
        { "condition": "AND", "key": "SqlUser", "operator": "=~", "value": "/^$SQLUSER$/" }
       ]
      }
     ]
    },
    {
     "title": "SqlXe -Query logical read",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "SqlQueryHash" ], "type": "tag" }
       ],
       "measurement": "sqlXeEvents",
       "query": "SELECT sum(\"logical_reads\") *8 FROM \"queryhashcodemetrics\".\"sqlXeEvents\" WHERE (\"AxUser\" =~ /^$USER$/ AND \"SqlHostName\" =~ /(?i)^$CLIENTHOST$/ AND \"SqlEventName\" =~ /^$sqleventname$/ AND \"SQLInstance\" =~ /(?i)^$SQLINSTANCE$/ AND \"SqlQueryHash\" =~ /^$QueryHash$/ AND \"AxSession\" =~ /^$SESSION$/ AND \"SqlUser\" =~ /^$SQLUSER$/) AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"SqlQueryHash\"",
       "select": [
        [
         { "params": [ "logical_reads" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "*8" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "SqlHostName", "operator": "=~", "value": "/^$CLIENTHOST$/" },
        { "condition": "AND", "key": "SqlEventName", "operator": "=~", "value": "/^$sqleventname$/" },
        { "condition": "AND", "key": "SQLInstance", "operator": "=~", "value": "/^$SQLINSTANCE$/" },
        { "condition": "AND", "key": "SqlQueryHash", "operator": "=~", "value": "/^$QueryHash$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" },
        { "condition": "AND", "key": "SqlUser", "operator": "=~", "value": "/^$SQLUSER$/" }
       ]
      }
     ]
    },
    {
     "title": "SqlXe -Query writes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "SqlQueryHash" ], "type": "tag" }
       ],
       "measurement": "sqlXeEvents",
       "query": "SELECT sum(\"writes\") *8 FROM \"queryhashcodemetrics\".\"sqlXeEvents\" WHERE (\"AxUser\" =~ /^$USER$/ AND \"SqlHostName\" =~ /(?i)^$CLIENTHOST$/ AND \"SqlEventName\" =~ /^$sqleventname$/ AND \"SQLInstance\" =~ /(?i)^$SQLINSTANCE$/ AND \"SqlQueryHash\" =~ /^$QueryHash$/ AND \"AxSession\" =~ /^$SESSION$/ AND \"SqlUser\" =~ /^$SQLUSER$/) AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"SqlQueryHash\"",
       "select": [
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "*8" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "SqlHostName", "operator": "=~", "value": "/^$CLIENTHOST$/" },
        { "condition": "AND", "key": "SqlEventName", "operator": "=~", "value": "/^$sqleventname$/" },
        { "condition": "AND", "key": "SQLInstance", "operator": "=~", "value": "/^$SQLINSTANCE$/" },
        { "condition": "AND", "key": "SqlQueryHash", "operator": "=~", "value": "/^$QueryHash$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" },
        { "condition": "AND", "key": "SqlUser", "operator": "=~", "value": "/^$SQLUSER$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "RPC ${SQLINSTANCE}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "SQLINSTANCE",
   "collapsed": true,
   "panels": [
    {
     "title": "Successful",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "SqlEventName" ], "type": "tag" }
       ],
       "measurement": "sqlXeEvents",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "SqlHostName", "operator": "=~", "value": "/^$CLIENTHOST$/" },
        { "condition": "AND", "key": "SqlEventName", "operator": "=", "value": "rpc_completed" },
        { "condition": "AND", "key": "SQLInstance", "operator": "=~", "value": "/^$SQLINSTANCE$/" },
        { "condition": "AND", "key": "result", "operator": "=", "value": "OK" },
        { "condition": "AND", "key": "SqlUser", "operator": "=~", "value": "/^$SQLUSER$/" }
       ]
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "SqlEventName" ], "type": "tag" }
       ],
       "measurement": "sqlXeEvents",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "SqlHostName", "operator": "=~", "value": "/^$CLIENTHOST$/" },
        { "condition": "AND", "key": "SqlEventName", "operator": "=", "value": "rpc_completed" },
        { "condition": "AND", "key": "SQLInstance", "operator": "=~", "value": "/^$SQLINSTANCE$/" },
        { "condition": "AND", "key": "result", "operator": "=", "value": "Error" },
        { "condition": "AND", "key": "SqlUser", "operator": "=~", "value": "/^$SQLUSER$/" }
       ]
      }
     ]
    },
    {
     "title": "Aborted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "SqlEventName" ], "type": "tag" }
       ],
       "measurement": "sqlXeEvents",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "SqlHostName", "operator": "=~", "value": "/^$CLIENTHOST$/" },
        { "condition": "AND", "key": "SqlEventName", "operator": "=", "value": "rpc_completed" },
        { "condition": "AND", "key": "SQLInstance", "operator": "=~", "value": "/^$SQLINSTANCE$/" },
        { "condition": "AND", "key": "result", "operator": "=", "value": "Abort" },
        { "condition": "AND", "key": "SqlUser", "operator": "=~", "value": "/^$SQLUSER$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "COUNTS ${SQLINSTANCE}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "repeat": "SQLINSTANCE",
   "collapsed": true,
   "panels": [
    {
     "title": "SqlXe -Query count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "SqlQueryHash" ], "type": "tag" }
       ],
       "measurement": "sqlXeEvents",
       "select": [
        [
         { "params": [ "logical_reads" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "SqlHostName", "operator": "=~", "value": "/^$CLIENTHOST$/" },
        { "condition": "AND", "key": "SqlEventName", "operator": "=~", "value": "/^$sqleventname$/" },
        { "condition": "AND", "key": "SQLInstance", "operator": "=~", "value": "/^$SQLINSTANCE$/" },
        { "condition": "AND", "key": "SqlQueryHash", "operator": "=~", "value": "/^$QueryHash$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" },
        { "condition": "AND", "key": "SqlUser", "operator": "=~", "value": "/^$SQLUSER$/" }
       ]
      }
     ]
    },
    {
     "title": "SqlXe -Query count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "SqlQueryHash" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "sqlXeEvents",
       "select": [
        [
         { "params": [ "logical_reads" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "SqlHostName", "operator": "=~", "value": "/^$CLIENTHOST$/" },
        { "condition": "AND", "key": "SqlEventName", "operator": "=~", "value": "/^$sqleventname$/" },
        { "condition": "AND", "key": "SQLInstance", "operator": "=~", "value": "/^$SQLINSTANCE$/" },
        { "condition": "AND", "key": "SqlQueryHash", "operator": "=~", "value": "/^$QueryHash$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" },
        { "condition": "AND", "key": "SqlUser", "operator": "=~", "value": "/^$SQLUSER$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "QUERIES ${SQLINSTANCE}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "repeat": "SQLINSTANCE",
   "collapsed": true,
   "panels": [
    {
     "title": " ",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"duration\", \"cpu_time\", \"logical_reads\"*8, \"physical_reads\"*8, row_count, \"writes\"*8, \"SqlQueryHash\",\"hex_query_hash\", \"queryplan_hash\",\"hex_queryplan_hash\", \"session_id\", \"AxSession\", \"AxUser\", \"SqlEventName\", \"SqlHostName\", \"SqlUser\", \"DatabaseName\", \"result\",\"isFetch\" FROM \"queryhashcodemetrics\".\"sqlXeEvents\" WHERE \"SqlQueryHash\" =~ /^$QueryHash$/ AND \"AxUser\" =~ /^$USER$/ AND \"SqlUser\" =~ /^$SQLUSER$/ AND \"SqlEventName\" =~ /^$sqleventname$/ AND \"SqlHostName\" =~ /^$CLIENTHOST$/ AND \"AxSession\" =~ /^$SESSION$/ AND  \"SQLInstance\" =~ /^$SQLINSTANCE$/ AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "FETCHES ${SQLINSTANCE}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "repeat": "SQLINSTANCE",
   "collapsed": true,
   "panels": [
    {
     "title": "Fetches - duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "query_hash" ], "type": "tag" }
       ],
       "measurement": "sqlXeFetches",
       "query": "SELECT sum(\"duration\") FROM \"queryhashcodemetrics\".\"sqlXeFetches\" WHERE (\"AxUser\" =~ /^$USER$/ AND \"AxSession\" =~ /^$SESSION$/ AND \"query_hash\" =~ /^$FetchesQueryHash$/ AND \"AxSession\" =~ /^$SESSION$/ AND \"SQLInstance\" =~ /(?i)^$SQLINSTANCE$/ AND \"SqlHostName\" =~ /(?i)^$CLIENTHOST$/ AND \"SqlUser\" =~ /^$SQLUSER$/) AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"query_hash\"",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" },
        { "condition": "AND", "key": "query_hash", "operator": "=~", "value": "/^$FetchesQueryHash$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" },
        { "condition": "AND", "key": "SQLInstance", "operator": "=~", "value": "/^$SQLINSTANCE$/" },
        { "condition": "AND", "key": "SqlHostName", "operator": "=~", "value": "/^$CLIENTHOST$/" },
        { "condition": "AND", "key": "SqlUser", "operator": "=~", "value": "/^$SQLUSER$/" }
       ]
      }
     ]
    },
    {
     "title": "FETCHES",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"duration\", \"cpu_time\", \"logical_reads\"*8, \"physical_reads\"*8, \"writes\"*8, \"row_count\",\"query_hash\", \"query_hash_hex\", \"query_plan_hash\", \"query_plan_hash_hex\", \"session_id\", \"AxSession\",\"AxUser\", \"SqlHostName\",\"SqlUser\", \"cursor_id\" FROM \"queryhashcodemetrics\".\"sqlXeFetches\" WHERE (\"AxUser\" =~ /^$USER$/ AND \"query_hash\" =~ /^$FetchesQueryHash$/ AND \"AxSession\" =~ /^$SESSION$/ AND \"SQLInstance\" =~ /^$SQLINSTANCE$/ AND \"SqlHostName\" =~ /^$CLIENTHOST$/ AND \"SqlUser\" =~ /^$SQLUSER$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}