dist: xenial
git:
  submodules: false

before_install:
- sudo apt update -y
- sudo apt install python3 python3-pip python3-virtualenv hunspell myspell-en-us -y
- virtualenv ci_pve && ci_pve/bin/pip install mistune pyyaml

script:
- ./ci_pve/bin/python ./.CI/check_yaml.py "."
- source ./ci_pve/bin/activate && ./.CI/spellchecker.sh && deactivate

