{
 "title": "Database Blocking/Deadlocks",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "AXSQLNODE",
    "label": "AXSQLNODE",
    "query": "SHOW TAG VALUES FROM \"SQLLongTransaction\" WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "Blocking Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "AX 2012",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "General_Statistics",
       "select": [
        [
         { "params": [ "Processes_blocked" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Blocked Processes" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$AXSQLNODE$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Locks",
       "select": [
        [
         { "params": [ "Number_of_Deadlocks_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Deadlocks/sec" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$AXSQLNODE$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Long Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Long Transaction AX 2012",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "ClientHostName" ], "type": "tag" },
        { "params": [ "LoginName" ], "type": "tag" },
        { "params": [ "AXUser" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "SQLLongTransaction",
       "select": [
        [
         { "params": [ "MaxDuration" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$AXSQLNODE$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Long Transaction Detials",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Long Transaction AX 2012",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "measurement": "SQLLongTransaction",
       "select": [
        [
         { "params": [ "ClientHostName" ], "type": "field" }
        ],
        [
         { "params": [ "AXUser" ], "type": "field" }
        ],
        [
         { "params": [ "LoginName" ], "type": "field" }
        ],
        [
         { "params": [ "MaxDuration" ], "type": "field" }
        ],
        [
         { "params": [ "MaxLastBatch" ], "type": "field" }
        ],
        [
         { "params": [ "NrSessions" ], "type": "field" }
        ],
        [
         { "params": [ "ALLAxSessions" ], "type": "field" }
        ],
        [
         { "params": [ "ALLSQLSessions" ], "type": "field" }
        ],
        [
         { "params": [ "ALLDurations" ], "type": "field" }
        ],
        [
         { "params": [ "MaxAxSession" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$AXSQLNODE$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Head Blockers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Head Blockers AX 2012",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "LoginName" ], "type": "tag" },
        { "params": [ "AXUser" ], "type": "tag" },
        { "params": [ "ClientHostName" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "SQLHeadBlockers",
       "query": "SELECT max(\"MaxVictimWaitInSec\") AS \"MaxWaitInSec\" FROM \"SQLHeadBlockers\" WHERE (\"host\" =~ /^$AXSQLNODE$/) AND $timeFilter GROUP BY time(1m), \"LoginName\", \"AXUser\", \"ClientHostName\" fill(0)",
       "select": [
        [
         { "params": [ "MaxWaitInSec" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "MaxWaitInSec" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$AXSQLNODE$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Head Blocker Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "HeadBlockers AX 2012",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "measurement": "SQLHeadBlockers",
       "query": "SELECT \"ALLWaitsInSecList\", \"MaxWaitInSec\",  \"MaxVictimWaitInSec\",\"NrOfWaitingSessions\" - 1, \"AXSession\", \"ClientHostName\", \"BlockedAxUsersChain\",  \"BlockedAxSessionsChain\",\"BlockedSQLSessionsChain\",BlockedSQLClientHostName FROM \"SQLHeadBlockers\" WHERE  \"host\" =~ /^$AXSQLNODE$/  AND $timeFilter",
       "select": [
        [
         { "params": [ "ALLWaitsInSecList" ], "type": "field" }
        ],
        [
         { "params": [ "MaxWaitInSec" ], "type": "field" }
        ],
        [
         { "params": [ "NrOfWaitingSessions" ], "type": "field" }
        ],
        [
         { "params": [ "AXSession" ], "type": "field" }
        ],
        [
         { "params": [ "ClientHostName" ], "type": "field" }
        ],
        [
         { "params": [ "BlockedAxUsersChain" ], "type": "field" }
        ],
        [
         { "params": [ "BlockedSQLSessionsChain" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DXSIPDB01" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deadlocks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "WaitObjectname" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "SQLDeadlockStats",
       "select": [
        [
         { "params": [ "NrOfVictims" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "NrOfDeadlocks" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$AXSQLNODE$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Deadlock Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deadlock Table",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "measurement": "SQLDeadlockStats",
       "select": [
        [
         { "params": [ "NrOfVictims" ], "type": "field" }
        ],
        [
         { "params": [ "WaitObject" ], "type": "field" }
        ],
        [
         { "params": [ "WaitIndex" ], "type": "field" }
        ],
        [
         { "params": [ "ClientHostName" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$AXSQLNODE$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}