{
 "title": "overview AX BATCH JOB PROD",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Overdue Batch Tasks in PROD",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "GROUPID" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AXBatchOverdueByGrp",
     "select": [
      [
       { "params": [ "cntBatchOverdue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Overdue" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "DBName", "operator": "=", "value": "AXPRODDB" }
     ]
    }
   ]
  },
  {
   "title": "AX Running BATCH Sessions PROD",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "AOSServer" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "AXBatchSessionOverviewByAOS",
     "select": [
      [
       { "params": [ "runningBatchSessions" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Running" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "DBName", "operator": "=", "value": "AXPRODDB" }
     ]
    }
   ]
  },
  {
   "title": "AX Free BATCH Sessions PROD",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "AOSServer" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "AXBatchSessionOverviewByAOS",
     "select": [
      [
       { "params": [ "freeBatchSessions" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "DBName", "operator": "=", "value": "AXPRODDB" }
     ]
    }
   ]
  },
  {
   "title": "BATCH AOS Processor Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Processor",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "WCPRODAOSBS01" },
      { "condition": "OR", "key": "host", "operator": "=", "value": "WCPRODAOSBS02" }
     ]
    }
   ]
  },
  {
   "title": "BATCH AOS available Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Memory",
     "select": [
      [
       { "params": [ "Available_KBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "WCPRODAOSBS01" },
      { "condition": "OR", "key": "host", "operator": "=", "value": "WCPRODAOSBS02" }
     ]
    }
   ]
  }
 ]
}