#!/bin/bash
#
# Startup script for all NetEye services
#
# chkconfig: - 99 1
# description: Start the NetEye Service

# Source function library.
. /etc/rc.d/init.d/functions

if [ -e /etc/sysconfig/neteye-extra-services ]
then
	. /etc/sysconfig/neteye-extra-services
fi

files_to_sync="/etc/nagios/nrpe.cfg /data/neteye/etc/smsd.conf"
dirs_to_sync="/usr/lib/nagios/plugins /etc/snmp /usr/share/snmp/mibs"

TMPFILE=/tmp/neteye_status$$.tmp
trap 'rm -f $TMPFILE; exit 1' 1 2 15
trap 'rm -f $TMPFILE' 0

MONITORINGDAEMON="nagios"
if [ -x /etc/init.d/monitoring-daemon ]
then
	MONITORINGDAEMON=$(/etc/init.d/monitoring-daemon prog)
fi

sync_files() {
	if [ ! -d /data/neteye/etc ]
	then
		return
	fi
	hh=`hostname -s`
	if [ "$hh" = "neteye01" ]
	then
		shost="neteye02int"
	else
		shost="neteye01int"
	fi
	if ! ping -c1 $shost >/dev/null 2>&1
	then
			echo "$shost not reachable, not syncing files"
			return
	fi
	if [ -s /data/neteye/etc/watchdog.conf ]
	then
		cp -u /data/neteye/etc/watchdog.conf /etc/sysconfig/watchdog
	fi
	for i in $files_to_sync
	do
		rsync -a $i $shost:$i
	done
	for i in $dirs_to_sync
	do
		dd=`dirname $i`
		rsync -a $i $shost:$dd/
	done
}

check_local_modem() {
        MODEMSTATUS=0
	# Check only if sms daemon is being run
	! chkconfig --list sms | grep 3:on >/dev/null 2>&1 && return 0

	# First check with our nagios plugin if modem is registerd and has signal
	/usr/lib/nagios/plugins/check_modem_smst.pl -c 1 >>$TMPFILE && return 0
        RETVAL_LOCAL_MODEM_REG=$?

        if [ $RETVAL_LOCAL_MODEM_REG -ne 0 ]
        then
		[ ! -e /etc/init.d/drbd-mount ] && MODEMSTATUS=66 && return
		hh=`hostname -s`
		if [ "$hh" = "neteye01" ]
		then
			shost="neteye02int"
		else
			shost="neteye01int"
		fi

                #If local problem detected check remote modem
                /usr/lib/nagios/plugins/check_nrpe -t 50 -H $shost -c check_sms_modem_reg >>$TMPFILE
                RETVAL_REMOTE_MODEM_REG=$?

                if [ $RETVAL_REMOTE_MODEM_REG -eq 0 ]
                then
                        echo "relocate suggested"
                        /usr/lib/nagios/plugins/check_nrpe -H $shost -c sms_notify -a ClusterSupport "NetEye cluster relocation to node $shost" >>$TMPFILE
                        MODEMSTATUS=66
                fi
        fi
}

check_neteye() {
	ret=0
	
	chkconfig --list drbd 2>/dev/null | grep 3:on >/dev/null 2>&1 && [ -e /etc/init.d/drbd-mount ] && ! /etc/init.d/drbd-mount status >>$TMPFILE && let "ret+=1" && rstr="$rstr drbd-mount"
	chkconfig --list drbd 2>/dev/null | grep 3:on >/dev/null 2>&1 && [ -e /etc/init.d/drbd-mount ] && allsrv=" drbd-mount"
	[ -e /etc/init.d/nfs-mount ] && ! /etc/init.d/nfs-mount status >>$TMPFILE && let "ret+=1" && rstr="$rstr nfs-mount"
	[ -e /etc/init.d/nfs-mount ] && allsrv="$allsrv nfs-mount"
	! /etc/init.d/monitoring-daemon status >>$TMPFILE && let "ret+=1" && rstr="$rstr $MONITORINGDAEMON"
	allsrv="$allsrv $MONITORINGDAEMON"
	[ -e /etc/init.d/gearmand ] && ! /etc/init.d/gearmand status >>$TMPFILE && let "ret+=1" && rstr="$rstr gearmand"
	[ -e /etc/init.d/gearmand ] && allsrv="$allsrv gearmand"
	[ -e /etc/init.d/mod_gearman_neteye ] && ! /etc/init.d/mod_gearman_neteye status >>$TMPFILE && let "ret+=1" && rstr="$rstr mod_gearman_neteye"
	[ -e /etc/init.d/mod_gearman_neteye ] && allsrv="$allsrv mod_gearman_neteye"
	! /etc/init.d/mysqld status >>$TMPFILE && let "ret+=1" && rstr="$rstr mysqld"
	allsrv="$allsrv mysqld"
	! /etc/init.d/httpd status >>$TMPFILE && let "ret+=1" && rstr="$rstr httpd"
	allsrv="$allsrv httpd"
	[ -e /etc/init.d/thruk ] && allsrv="$allsrv thruk"
	[ -e /etc/init.d/smb ] && ! /etc/init.d/smb status >>$TMPFILE && let "ret+=1" && rstr="$rstr smb"
	[ -e /etc/init.d/smb ] && allsrv="$allsrv smb"
	[ -e /etc/init.d/influxdb ] && ! /etc/init.d/influxdb status >>$TMPFILE && rstr="$rstr influxdb"
	[ -e /etc/init.d/influxdb ] && allsrv="$allsrv influxdb"
	[ -e /etc/init.d/grafana-server ] && ! /etc/init.d/grafana-server status >>$TMPFILE && let "ret+=1" && rstr="$rstr grafana-server"
	[ -e /etc/init.d/grafana-server ] && allsrv="$allsrv grafana-server"
	[ -e /etc/init.d/npcd ] && ! /etc/init.d/npcd status >>$TMPFILE && let "ret+=1" && rstr="$rstr npcd"
	[ -e /etc/init.d/npcd ] && allsrv="$allsrv npcd"
	chkconfig --list snmpd | grep 3:on >/dev/null 2>&1 && ! /etc/init.d/snmpd status >>$TMPFILE && let "ret+=1" && rstr="$rstr snmpd"
	chkconfig --list snmpd | grep 3:on >/dev/null 2>&1 && allsrv="$allsrv snmpd"
	! /etc/init.d/snmptrapd status >>$TMPFILE && let "ret+=1" && rstr="$rstr snmptrapd"
	allsrv="$allsrv snmptrapd"
	[ -e /etc/init.d/eventhandlerd ] && ! /etc/init.d/eventhandlerd status >>$TMPFILE && rstr="$rstr eventhandlerd"
	[ -e /etc/init.d/eventhandlerd ] && allsrv="$allsrv eventhandlerd"
	! /etc/init.d/rrdcached status >>$TMPFILE && rstr="$rstr rrdcached"
	allsrv="$allsrv rrdcached"
	[ -e /etc/init.d/rsyslog ] && ! /etc/init.d/rsyslog status >>$TMPFILE && rstr="$rstr rsyslog"
	[ -e /etc/init.d/rsyslog ] && allsrv="$allsrv rsyslog"
	[ ! -e /etc/init.d/rsyslog ] && ! /etc/init.d/syslog status >>$TMPFILE && rstr="$rstr syslog"
	[ ! -e /etc/init.d/rsyslog ] && allsrv="$allsrv syslog"
	! /etc/init.d/crond status >>$TMPFILE && let "ret+=1" && rstr="$rstr crond"
	allsrv="$allsrv crond"
	chkconfig --list sms | grep 3:on >/dev/null 2>&1 && ! /usr/lib/nagios/plugins/check_procs -C smsd -c 1: >>$TMPFILE && rstr="$rstr smsd"
	chkconfig --list sms | grep 3:on >/dev/null 2>&1 && allsrv="$allsrv smsd"
	chkconfig --list sms | grep 3:on >/dev/null 2>&1 && [ -e /etc/init.d/watchdog ] && ! /etc/init.d/watchdog status >>$TMPFILE && rstr="$rstr watchdog"
	chkconfig --list sms | grep 3:on >/dev/null 2>&1 && [ -e /etc/init.d/watchdog ] && allsrv="$allsrv watchdog"
	[ -e /etc/init.d/nfsen ] && ! /etc/init.d/nfsen status >>$TMPFILE && let "ret+=1" && rstr="$rstr nfsen"
	[ -e /etc/init.d/nfsen ] && allsrv="$allsrv nfsen"
	#Check Sahi: Running only Pro or in ALTERNATIVE OpenSource
	if [ -e /etc/init.d/sahipro ]; then
	   /etc/init.d/sahipro status | grep "stopped"  >>$TMPFILE && let "ret+=1" && rstr="$rstr sahipro"
	   allsrv="$allsrv sahipro"
	elif [ -e /etc/init.d/sahi ]; then
	   /etc/init.d/sahi status | grep "stopped"  >>$TMPFILE && let "ret+=1" && rstr="$rstr sahi"
	   allsrv="$allsrv sahi"
	fi
	[ -e /etc/init.d/nedi ] && ! /etc/init.d/nedi status >>$TMPFILE && let "ret+=1" && rstr="$rstr nedi"
	[ -e /etc/init.d/nedi ] && allsrv="$allsrv nedi"
	[ -e /etc/init.d/collectd ] && ! /etc/init.d/collectd status >>$TMPFILE && let "ret+=1" && rstr="$rstr collectd"
	[ -e /etc/init.d/collectd ] && allsrv="$allsrv collectd"
	[ -e /etc/init.d/tomcat6 ] && ! /etc/init.d/tomcat6 status >>$TMPFILE && let "ret+=1" && rstr="$rstr tomcat6"
	[ -e /etc/init.d/tomcat6 ] && allsrv="$allsrv tomcat6"
	[ -e /etc/init.d/redis ] && ! /etc/init.d/redis status >>$TMPFILE && let "ret+=1" && rstr="$rstr redis"
	[ -e /etc/init.d/redis ] && allsrv="$allsrv redis"
	[ -e /etc/init.d/elasticsearch ] && ! /etc/init.d/elasticsearch status >>$TMPFILE && let "ret+=1" && rstr="$rstr elasticsearch"
	[ -e /etc/init.d/elasticsearch ] && allsrv="$allsrv elasticsearch"
	[ -e /etc/init.d/logstash ] && ! /etc/init.d/logstash status >>$TMPFILE && let "ret+=1" && rstr="$rstr logstash"
	[ -e /etc/init.d/logstash ] && allsrv="$allsrv logstash"
	[ -e /etc/init.d/kibana ] && ! /etc/init.d/kibana status >>$TMPFILE && let "ret+=1" && rstr="$rstr kibana"
	[ -e /etc/init.d/kibana ] && allsrv="$allsrv kibana"
	[ -e /etc/init.d/kibana4 ] && ! /etc/init.d/kibana4 status >>$TMPFILE && let "ret+=1" && rstr="$rstr kibana4"
	[ -e /etc/init.d/kibana4 ] && allsrv="$allsrv kibana4"
	[ -e /etc/init.d/monitoring-cache ] && ! /etc/init.d/monitoring-cache status >>$TMPFILE && rstr="$rstr monitoring-cache"
	[ -e /etc/init.d/monitoring-cache ] && allsrv="$allsrv monitoring-cache"
	[ -e /etc/init.d/nagflux ] && ! /etc/init.d/nagflux status >>$TMPFILE && rstr="$rstr nagflux"
	[ -e /etc/init.d/nagflux ] && allsrv="$allsrv nagflux"
	[ -e /etc/init.d/neteye-virtual-ip ] && ! /etc/init.d/neteye-virtual-ip status >>$TMPFILE && let "ret+=1" && rstr="$rstr virtual-ip"
	[ -e /etc/init.d/neteye-virtual-ip ] && allsrv="$allsrv virtual-ip"
	n=100
	for i in $NETEYE_EXTRA_SERVICES
	do
		n=$(expr $n + 1)
		if [ -e /etc/init.d/$i ]
		then
        		! /etc/init.d/$i status >>$TMPFILE && let "ret+=1" && rstr="$rstr $i"
			allsrv="$allsrv $i"
		fi
	done
	check_local_modem
	[ $MODEMSTATUS -gt 0 ] && let "ret+=66" && rstr="$rstr modem"

	RETSTATUS=$ret
	runsrv=$allsrv
	for nn in $rstr
	do
		runsrv=$(echo "$runsrv" | sed -e "s/ $nn//g")
	done
	if [ "$1" = "nagios" ]
	then
		if [ $RETSTATUS -ne 0 ]
		then
			echo "CRITICAL - ERROR some modules are not running: $rstr ($runsrv )";
			RETSTATUS=2
		elif [ -n "$rstr" ]
		then
			echo "WARNING - some modules are not running: $rstr ($runsrv )";
			RETSTATUS=1
		else
			echo "OK - All Services running ($runsrv )"
		fi
	else
		if [ $RETSTATUS -ne 0 ]
		then
			echo "ERROR some modules are not running: $rstr ($runsrv )";
		elif [ -n "$rstr" ]
		then
			echo "WARNING some modules are not running: $rstr ($runsrv )";
		else
			echo "All Services running ($runsrv )"
		fi
	fi
	echo -e "STATUS: $ret\nRUNNING: $runsrv\nNOT_RUNNING: $rstr\nALL: $allsrv" >/dev/shm/neteye.status 2>/dev/null
	if [ $RETSTATUS -ne 0 ]
	then
		echo -e "STATUS: $ret\nRUNNING: $runsrv\nNOT_RUNNING: $rstr\nALL: $allsrv" >/dev/shm/neteye_error.status 2>/dev/null
		echo "$(date): NOT_RUNNING: $rstr" >>/var/log/neteye/neteye_service_error_status.log 2>/dev/null
	elif [ -n "$rstr" ]
	then
		echo -e "STATUS: $ret\nRUNNING: $runsrv\nNOT_RUNNING: $rstr\nALL: $allsrv" >/dev/shm/neteye_warning.status 2>/dev/null
	fi
}

start_neteye_services() {

	if [ -e /etc/init.d/redis ]
	then
        /etc/init.d/redis start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 91
	fi
	if [ -e /etc/init.d/elasticsearch ]
	then
        	/etc/init.d/elasticsearch start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 21
	fi
	if [ -e /etc/init.d/logstash ]
	then
        	/etc/init.d/logstash start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 22
	fi
	if [ -e /etc/init.d/kibana ]
	then
        	/etc/init.d/kibana start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 24
	fi
	if [ -e /etc/init.d/kibana4 ]
	then
        	/etc/init.d/kibana4 start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 25
	fi
	if [ -e /etc/init.d/gearmand ]
	then
        	/etc/init.d/gearmand start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 75
	fi
	if [ -e /etc/init.d/mod_gearman_neteye ]
	then
		/etc/init.d/mod_gearman_neteye start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 76
	fi

	if chkconfig --list sms | grep 3:on >/dev/null 2>&1
	then
	  /etc/init.d/sms restart
	  RETVAL=$?
	  [ $RETVAL -ne 0 ] && exit 12
        fi
	if chkconfig --list snmpd | grep 3:on >/dev/null 2>&1
	then
	  service snmpd restart
	  RETVAL=$?
	  [ $RETVAL -ne 0 ] && exit 14
        fi
	service snmptrapd restart
	RETVAL=$?
	[ $RETVAL -ne 0 ] && exit 16
	service rrdcached restart
	RETVAL=$?
	[ $RETVAL -ne 0 ] && exit 17
	if [ -e /etc/init.d/influxdb ]
	then
           /etc/init.d/influxdb start
	   COUNTER=0
 	   TIMEOUT=60
	   while [ $COUNTER -lt $TIMEOUT ]
	   do
              ((COUNTER++))
              #influx --execute 'SHOW DATABASES' &> /dev/null
              /usr/lib/nagios/plugins/check_tcp -H localhost -p 8086 >/dev/null
              if [ $? -eq 0 ]; then
                 break
              fi
              sleep 1
           done
	   # ZAPA: Start of cluster fails with ret.code 62. Start of influx takes too long.
	   #RETVAL=$?
	   #[ $RETVAL -ne 0 ] && exit 62
	fi
	if [ -e /etc/init.d/nfsen ]
	then
	  service nfsen start
	  RETVAL=$?
	  [ $RETVAL -ne 0 ] && exit 18
	fi

	#Sahi/Sahipro Start: Running only Pro or in ALTERNATIVE OpenSource
        if [ -e /etc/init.d/sahipro ]
        then
           service sahipro start
           RETVAL=$?
           [ $RETVAL -ne 0 ] && echo "Sahipro did not start on time. RetCode: $RETVAL. Continue with other services..."
           # exit 19
        elif [ -e /etc/init.d/sahi ]
        then
           service sahi start
           RETVAL=$?
           [ $RETVAL -ne 0 ] && echo "Sahi did not start on time. RetCode: $RETVAL. Continue with other services..."
           #exit 20
        fi 

	service mysqld start
	RETVAL=$?
	[ $RETVAL -ne 0 ] && exit 20
	
	# generate rsyslog configuration before restarting
	/usr/bin/perl /var/lib/neteye/plugins/nesyslogview/scripts/applyRsyslogConfiguration.pl -q
	if [ -e /etc/init.d/rsyslog ]
	then
        	/etc/init.d/rsyslog restart
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 23
	fi

	if [ -e /etc/init.d/ndo2db ]
	then
		[ -e /var/log/nagios/rw/ndo.sock ] && rm -f /var/log/nagios/rw/ndo.sock
		service ndo2db start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 30
	fi

	/etc/init.d/httpd start
	RETVAL=$?
	[ $RETVAL -ne 0 ] && exit 40
	if [ -e /etc/init.d/smokeping ]
	then
		/etc/init.d/smokeping start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 50
	fi
	if [ -e /etc/init.d/smb ]
	then
		/etc/init.d/smb start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 60
	fi
	if [ -e /etc/init.d/grafana-server ]
	then
        	/etc/init.d/grafana-server start
		#RETVAL=$?
		#[ $RETVAL -ne 0 ] && exit 64
		COUNTER=0
		TIMEOUT=60
		while [ $COUNTER -lt $TIMEOUT ]
 		do
                   ((COUNTER++))
                   /etc/init.d/grafana-server status >/dev/null
                   if [ $? -eq 0 ]; then
                      break
                   fi
                   sleep 1
                done
	fi
	if [ -e /etc/init.d/npcd ]
	then
        	/etc/init.d/npcd start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 70
	fi
	if [ -e /etc/init.d/tomcat6 ]
	then
        	/etc/init.d/tomcat6 start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 71
	fi
        if /etc/init.d/monitoring-daemon status >/dev/null
	then
		/etc/init.d/monitoring-daemon restart
		RETVAL=$?
	else
		/etc/init.d/monitoring-daemon start
		RETVAL=$?
	fi
	if [ -e /etc/init.d/nedi ]
	then
	  service nedi start
	  RETVAL=$?
	  [ $RETVAL -ne 0 ] && exit 74
	fi
	if [ -e /etc/init.d/collectd ]
	then
		/etc/init.d/collectd start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 77
	fi
	[ $RETVAL -ne 0 ] && exit 80
	if [ -e /etc/init.d/thruk ]
	then
        	/etc/init.d/thruk start
	fi
	if [ -e /etc/init.d/eventhandlerd ]
	then
        	/etc/init.d/eventhandlerd start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 78
	fi
	if [ -e /etc/init.d/monitoring-cache ]
	then
		/etc/init.d/monitoring-cache start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 81
	fi
	if [ -e /etc/init.d/nagflux ]
	then
		/etc/init.d/nagflux start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 81
	fi
	if chkconfig --list sms | grep 3:on >/dev/null 2>&1
	then
	  [ -x /etc/init.d/watchdog ] && /etc/init.d/watchdog start
	  RETVAL=0
	fi
	n=100
	for i in $NETEYE_EXTRA_SERVICES
	do
		n=$(expr $n + 1)
		if [ -e /etc/init.d/$i ]
		then
        		/etc/init.d/$i start
			RETVAL=$?
			[ $RETVAL -ne 0 ] && exit $n
		fi
	done
}

restart_neteye_services() {
    if [ -e /etc/init.d/redis ]; then
        /etc/init.d/redis status >/dev/null || /etc/init.d/redis start
        RETVAL=$?
        [ $RETVAL -ne 0 ] && exit 91
	fi
	/etc/init.d/elasticsearch status >/dev/null || service elasticsearch start
	RETVAL=$?
	[ $RETVAL -ne 0 ] && exit 21
	/etc/init.d/logstash status >/dev/null || service logstash start
	RETVAL=$?
	[ $RETVAL -ne 0 ] && exit 22
	/etc/init.d/rsyslog status >/dev/null || service rsyslog start
	RETVAL=$?
	[ $RETVAL -ne 0 ] && exit 23
	/etc/init.d/kibana status >/dev/null || service kibana start
	RETVAL=$?
	[ $RETVAL -ne 0 ] && exit 24
	/etc/init.d/kibana4 status >/dev/null || service kibana4 start
	RETVAL=$?
	[ $RETVAL -ne 0 ] && exit 25
	if [ -e /etc/init.d/gearmand ]
	then
        	/etc/init.d/gearmand status >/dev/null || /etc/init.d/gearmand start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 75
	fi
	if [ -e /etc/init.d/mod_gearman_neteye ]
	then
        	/etc/init.d/mod_gearman_neteye status >/dev/null || /etc/init.d/mod_gearman_neteye start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 76
	fi
	if chkconfig --list sms | grep 3:on >/dev/null 2>&1
	then
	  /usr/lib/nagios/plugins/check_procs -C smsd -c 1: >/dev/null || /etc/init.d/sms start
	  RETVAL=$?
	  [ $RETVAL -ne 0 ] && exit 12
        fi
	if chkconfig --list snmpd | grep 3:on >/dev/null 2>&1
	then
	  /usr/lib/nagios/plugins/check_procs -C snmpd -c 1: >/dev/null || service snmpd start
	  RETVAL=$?
	  [ $RETVAL -ne 0 ] && exit 14
        fi
	/etc/init.d/snmptrapd status >/dev/null || service snmptrapd start
	RETVAL=$?
	[ $RETVAL -ne 0 ] && exit 16
	/etc/init.d/rrdcached status >/dev/null || service rrdcached start
	RETVAL=$?
	[ $RETVAL -ne 0 ] && exit 17
	if [ -e /etc/init.d/influxdb ]
	then
        	/etc/init.d/influxdb status >/dev/null || /etc/init.d/influxdb start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 70
	fi
	if [ -e /etc/init.d/nfsen ]
	then
	  /etc/init.d/nfsen status >/dev/null || service nfsen start
	  RETVAL=$?
	  [ $RETVAL -ne 0 ] && exit 18
	fi
	
	#Sahi Status
	if [ -e /etc/init.d/sahipro ]
        then
           ! /etc/init.d/sahipro status | grep "stopped" >/dev/null || /etc/init.d/sahipro start
           RETVAL=$?
           [ $RETVAL -ne 0 ] && exit 19
	elif [ -e /etc/init.d/sahi ]
        then
          ! /etc/init.d/sahi status | grep "stopped" > /dev/null || /etc/init.d/sahi start
          RETVAL=$?
          [ $RETVAL -ne 0 ] && exit 20
        fi

	/etc/init.d/mysqld status >/dev/null || service mysqld start
	RETVAL=$?
	[ $RETVAL -ne 0 ] && exit 20
	if [ -e /etc/init.d/ndo2db ]
	then
		[ -e /var/log/nagios/rw/ndo.sock ] && rm -f /var/log/nagios/rw/ndo.sock
		/etc/init.d/ndo2db status >/dev/null || service ndo2db start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 30
	fi
	/etc/init.d/httpd status >/dev/null || /etc/init.d/httpd start
	RETVAL=$?
	[ $RETVAL -ne 0 ] && exit 40
	if [ -e /etc/init.d/smokeping ]
	then
		/etc/init.d/smokeping status >/dev/null || /etc/init.d/smokeping start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 50
	fi
	if [ -e /etc/init.d/smb ]
	then
		/etc/init.d/smb status >/dev/null || /etc/init.d/smb start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 60
	fi
	if [ -e /etc/init.d/grafana-server ]
	then
        	/etc/init.d/grafana-server status >/dev/null || /etc/init.d/grafana-server start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 70
	fi
	if [ -e /etc/init.d/npcd ]
	then
        	/etc/init.d/npcd status >/dev/null || /etc/init.d/npcd start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 70
	fi
	if [ -e /etc/init.d/tomcat6 ]
	then
        	/etc/init.d/tomcat6 status >/dev/null || /etc/init.d/tomcat6 start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 71
	fi
	if [ -e /etc/init.d/nedi ]
	then
	  /etc/init.d/nedi status >/dev/null || service nedi start
	  RETVAL=$?
	  [ $RETVAL -ne 0 ] && exit 74
	fi
	if [ -e /etc/init.d/collectd ]
	then
        	/etc/init.d/collectd status >/dev/null || /etc/init.d/collectd start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 77
	fi
        /etc/init.d/monitoring-daemon status >/dev/null || /etc/init.d/monitoring-daemon start
	RETVAL=$?
	[ $RETVAL -ne 0 ] && exit 80
	if [ -e /etc/init.d/thruk ]
	then
        	/etc/init.d/thruk status >/dev/null || /etc/init.d/thruk start
	fi
	if [ -e /etc/init.d/eventhandlerd ]
	then
        	/etc/init.d/eventhandlerd status >/dev/null || /etc/init.d/eventhandlerd start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 78
	fi
	if [ -e /etc/init.d/monitoring-cache ]
	then
        	/etc/init.d/monitoring-cache status >/dev/null || /etc/init.d/monitoring-cache start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 81
	fi
	if [ -e /etc/init.d/nagflux ]
	then
        	/etc/init.d/nagflux status >/dev/null || /etc/init.d/nagflux start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 81
	fi
	n=100
	for i in $NETEYE_EXTRA_SERVICES
	do
		n=$(expr $n + 1)
		if [ -e /etc/init.d/$i ]
		then
        		/etc/init.d/$i status >/dev/null || /etc/init.d/$i start
			RETVAL=$?
			[ $RETVAL -ne 0 ] && exit $n
		fi
	done
}
case "$1" in
    start)
        if [ -e /var/lock/lock-neteye-service ]
        then
		echo "NetEye Status Locked"
                exit 0
        fi

	if [ -e /etc/init.d/drbd-mount ]
	then
		# We are in Cluster Environment
		service drbd-mount start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 10
		# Syncronize /data files to remote local filesystem
		sync_files
		[ ! -e /etc/init.d/rsyslog ] && /etc/init.d/syslog restart
	fi

	if [ -e /etc/init.d/nfs-mount ]
	then
		service nfs-mount start
		RETVAL=$?
		[ $RETVAL -ne 0 ] && exit 11
	fi

	if [ -e /etc/init.d/neteye-virtual-ip ]
	then
		/etc/init.d/neteye-virtual-ip start
	fi

	# Now start all NetEye Services
	start_neteye_services

	# We don't want this as it could shut down the cluster service on a Modem malfunction!
	#Finally check the status of the local and remote modem
	#check_local_modem
	#if [ $MODEMSTATUS -gt 0 ]
	#then
	#	exit $MODEMSTATUS
	#fi


	touch /var/lock/subsys/neteye

	exit 0
        ;;
        
    restart)
	# Here only try to start partially started NetEye Services
	restart_neteye_services
	touch /var/lock/subsys/neteye
	exit 0
	;;

    stop) 
        if [ -e /var/lock/lock-neteye-service ]
        then
		echo "NetEye Status Locked"
                exit 0
        fi

	rm -f /var/lock/subsys/neteye

    # here we want to assure that both (nagios and naemon) are stopped
    service nagios stop
    service naemon stop
	[ -e /etc/init.d/neteye-virtual-ip ] && /etc/init.d/neteye-virtual-ip stop
	n=100
	for i in $NETEYE_EXTRA_SERVICES
	do
		n=$(expr $n + 1)
		if [ -e /etc/init.d/$i ]
		then
        		/etc/init.d/$i stop
		fi
	done
	[ -e /etc/init.d/mod_gearman_neteye ] && service mod_gearman_neteye stop
	[ -e /etc/init.d/gearmand ] && service gearmand stop
        [ -e /etc/init.d/grafana-server ] && service grafana-server stop
        [ -e /etc/init.d/npcd ] && service npcd stop
	[ -e /etc/init.d/smb ] && service smb stop
	[ -e /etc/init.d/thruk ] && service thruk stop
	service httpd stop
        [ -e /etc/init.d/smokeping ] && service smokeping stop
	[ -e /etc/init.d/ndo2db ] && service ndo2db stop
	service mysqld stop
	[ -e /etc/init.d/nfsen ] && service nfsen stop
	[ -e /etc/init.d/influxdb ] && service influxdb stop
	#Stop Sahi
	[ -e /etc/init.d/sahipro ] && service sahipro stop
	[ -e /etc/init.d/sahi ] && service sahi stop
	[ -e /etc/init.d/tomcat6 ] && service tomcat6 stop
	[ -e /etc/init.d/collectd ] && service collectd stop
	[ -e /etc/init.d/nedi ] && service nedi stop
	service snmptrapd stop
	[ -e /etc/init.d/rrdcached ] && service rrdcached stop
	[ -e /etc/init.d/watchdog ] && service watchdog stop

	[ -e /etc/init.d/nfs-mount ] && service nfs-mount stop
	[ -e /etc/init.d/logstash ] && service logstash stop
	[ -e /etc/init.d/kibana ] && service kibana stop
	[ -e /etc/init.d/kibana4 ] && service kibana4 stop
	[ -e /etc/init.d/eventhandlerd ] && service eventhandlerd stop
	[ -e /etc/init.d/monitoring-cache ] && service monitoring-cache stop
	[ -e /etc/init.d/nagflux ] && service nagflux stop
	RET=0
	if [ -e /etc/init.d/drbd-mount ]
	then
		if [ -d /data/neteye/etc ]
		then
			# We are in Cluster environment
			# Syncronize local file to /data filesystem
			if [ ! -h /etc/smsd.conf ]
			then
				cp -f /etc/smsd.conf /data/neteye/etc
			fi
			if [ -s /etc/sysconfig/watchdog -a ! -h /etc/sysconfig/watchdog ]
			then
				cp -u /etc/sysconfig/watchdog /data/neteye/etc/watchdog.conf
			fi
		fi
		service drbd-mount stop
		RET=$?
		# restore a clean rsyslog.conf
		cat /var/lib/neteye/plugins/nesyslogview/etc/rsyslog.conf.header > /etc/rsyslog.conf
		[ -e /etc/init.d/rsyslog ] && /etc/init.d/rsyslog restart
		[ ! -e /etc/init.d/rsyslog ] && /etc/init.d/syslog restart
	fi

	exit $RET
        ;;
        
    status)
        if [ -e /var/lock/lock-neteye-service ]
        then
		echo "NetEye Status Locked"
                exit 0
        fi

	#
	# For NetEye Cluster sync important files permanently
	#
	if [ -d /data/neteye/etc ]
	then
		if [ -s /etc/sysconfig/watchdog ]
		then
			cp -u /etc/sysconfig/watchdog /data/neteye/etc/watchdog.conf
		fi
	fi

	check_neteye
	cat $TMPFILE

	exit $RETSTATUS
	;;

    monitor)
	check_neteye nagios

	exit $RETSTATUS
	;;

    lock)
	touch /var/lock/lock-neteye-service
	;;
	
    unlock)
	rm -f /var/lock/lock-neteye-service
	;;
	
    *)
	echo "Usage: $0 {start|stop|status|monitor|lock|unlock}"
	exit 10
	;;
esac

exit 0
