{
 "title": "Overview AX BATCH JOB",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "SISTEMA", "query": "influxdb" },
   {
    "name": "DBname",
    "label": "AX Env DB name",
    "query": "show tag values from  AXBatchSessionOverviewByAOS with key=DBName"
   },
   {
    "name": "AOSBATCHSERVERS",
    "query": "de-ffm-s-aos217,de-ffm-s-aos218,de-ffm-s-aos223,de-ffm-s-aos224"
   },
   {
    "name": "AOSBATCHSERVERSQry",
    "label": "AX Env DB name",
    "query": "show tag values from  AXBatchSessionOverviewByAOS with key=host"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Overdue Batch Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "GROUPID" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AXBatchOverdueByGrp",
     "select": [
      [
       { "params": [ "cntBatchOverdue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Overdue" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "DBName", "operator": "=~", "value": "/^$DBname$/" }
     ]
    }
   ]
  },
  {
   "title": "AX Running BATCH Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "AOSServer" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "AXBatchSessionOverviewByAOS",
     "select": [
      [
       { "params": [ "runningBatchSessions" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Running" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "DBName", "operator": "=~", "value": "/^$DBname$/" }
     ]
    }
   ]
  },
  {
   "title": "AX Free BATCH Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "AOSServer" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "AXBatchSessionOverviewByAOS",
     "select": [
      [
       { "params": [ "freeBatchSessions" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "DBName", "operator": "=~", "value": "/^$DBname$/" }
     ]
    }
   ]
  },
  {
   "title": "BATCH AOS Processor Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Processor",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$AOSBATCHSERVERS$/" },
      { "condition": "OR", "key": "host", "operator": "=~", "value": "/^$AOSBATCHSERVERSQry$/" }
     ]
    }
   ]
  },
  {
   "title": "BATCH AOS available Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Memory",
     "select": [
      [
       { "params": [ "Available_KBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$AOSBATCHSERVERS$/" },
      { "condition": "OR", "key": "host", "operator": "=~", "value": "/^$AOSBATCHSERVERSQry$/" }
     ]
    }
   ]
  }
 ]
}