# neteye test instance should point to internal pulp repo
#
- name: Disable mirror rebuild Add "when false" to tasks if missing
  ansible.builtin.replace:
    path: "{{path_neteye_ansible_file}}"
    regexp: '^(\s{4})(?!#)(.*)'
    replace: '#\2'
