{
 "title": "Alyvix - Troubleshooting View",
 "time": { "from": "2018-03-10T19:36:00.022Z", "to": "2018-07-03T03:27:05.452Z" },
 "templating": {
  "list": [
   {
    "name": "test_cases",
    "label": "Test Case",
    "query": "SHOW TAG VALUES FROM \"alyvix\" with KEY = test_name"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"alyvix\" with KEY = host"
   },
   {
    "name": "state_of_interest",
    "query": "warning, critical, timedout, not_executed"
   },
   {
    "name": "transactions",
    "label": "Transactions",
    "query": "SHOW TAG VALUES FROM \"alyvix\" with KEY = transaction_name where test_name =~ /^$test_cases$/"
   }
  ]
 },
 "panels": [
  { "title": "Cumulative Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Test Transaction Overview | $test_cases | $host",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "repeat": "host",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction_name - $tag_state",
     "groupBy": [
      { "params": [ "transaction_name" ], "type": "tag" },
      { "params": [ "state" ], "type": "tag" }
     ],
     "measurement": "alyvix",
     "query": "SELECT \"cumulative\" FROM \"alyvix\" WHERE \"test_name\" =~ /^$test_cases$/ AND \"host\" =~ /^$host$/ AND \"transaction_name\" =~ /^$transactions$/ AND $timeFilter GROUP BY \"transaction_name\", \"state\", \"point\"",
     "select": [
      [
       { "params": [ "cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "test_name", "operator": "=~", "value": "/^$test_cases$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "transaction_name", "operator": "=~", "value": "/^$transactions$/" }
     ]
    }
   ]
  },
  { "title": "Detailed Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Performances | $test_cases| $host",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "repeat": "host",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction_name",
     "groupBy": [
      { "params": [ "transaction_name" ], "type": "tag" }
     ],
     "measurement": "alyvix",
     "query": "C SELECT \"cumulative\" FROM \"alyvix\" WHERE \"test_name\" =~ /^$test_cases$/ AND \"host\" =~ /^$host$/ AND \"transaction_name\" =~ /^$transactions$/ AND $timeFilter GROUP BY \"transaction_name\", \"state\"",
     "select": [
      [
       { "params": [ "performance" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "test_name", "operator": "=~", "value": "/^$test_cases$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "transaction_name", "operator": "=~", "value": "/^$transactions$/" }
     ]
    },
    {
     "alias": "$tag_transaction_name  - $tag_state",
     "groupBy": [
      { "params": [ "transaction_name" ], "type": "tag" },
      { "params": [ "state" ], "type": "tag" }
     ],
     "measurement": "alyvix",
     "query": "C SELECT \"cumulative\" FROM \"alyvix\" WHERE \"test_name\" =~ /^$test_cases$/ AND \"host\" =~ /^$host$/ AND \"transaction_name\" =~ /^$transactions$/ AND $timeFilter GROUP BY \"transaction_name\", \"state\"",
     "select": [
      [
       { "params": [ "performance" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "test_name", "operator": "=~", "value": "/^$test_cases$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "transaction_name", "operator": "=~", "value": "/^$transactions$/" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state_of_interest$/" }
     ]
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "WARNING | CRITICAL | TIMEDOUT",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "repeat": "host",
   "targets": [
    {
     "alias": "$tag_state | $tag_transaction_name",
     "groupBy": [
      { "params": [ "transaction_name" ], "type": "tag" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "test_name" ], "type": "tag" }
     ],
     "measurement": "alyvix",
     "query": "SELECT \"performance\" FROM \"alyvix\" WHERE \"host\" =~ /^$host$/ AND \"test_name\" =~ /^$test_cases$/ AND $timeFilter GROUP BY \"transaction_name\", \"state\", \"test_name\"",
     "select": [
      [
       { "params": [ "performance" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "test_name", "operator": "=~", "value": "/^$test_cases$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "state", "operator": "!=", "value": "ok" },
      { "condition": "AND", "key": "transaction_name", "operator": "=~", "value": "/^$transactions$/" }
     ]
    }
   ]
  },
  {
   "title": "Troubleshooting Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "TROUBLESHOOTING INFO - $test_cases - $host",
     "type": "table",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
     "repeat": "host",
     "targets": [
      {
       "alias": "[[col]]",
       "groupBy": [
        { "params": [ "test_name" ], "type": "tag" }
       ],
       "measurement": "alyvix",
       "query": "SELECT \"aos_name\" AS \"AOS\", \"session_id\" AS \"Session ID\", \"ax_client_hostname\" AS \"Ax Client Hostname\" FROM \"alyvix\" WHERE \"test_name\" =~ /^$test_cases$/ AND \"host\" =~ /^$host$/ AND \"transaction_name\" =~ /^$transactions$/ AND $timeFilter GROUP BY \"test_name\"",
       "select": [
        [
         { "params": [ "aos_name" ], "type": "field" },
         { "params": [ "AOS" ], "type": "alias" }
        ],
        [
         { "params": [ "session_id" ], "type": "field" },
         { "params": [ "Session ID" ], "type": "alias" }
        ],
        [
         { "params": [ "ax_client_hostname" ], "type": "field" },
         { "params": [ "Ax Client Hostname" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "test_name", "operator": "=~", "value": "/^$test_cases$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "transaction_name", "operator": "=~", "value": "/^$transactions$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}