{
 "title": "WLC Clients",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Wireless Devices",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "TCliMAC" ], "type": "tag" }
     ],
     "measurement": "bsnMobileStationTable",
     "select": [
      [
       { "params": [ "CliIP" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Address" ], "type": "alias" }
      ],
      [
       { "params": [ "CliUserName" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "User" ], "type": "alias" }
      ],
      [
       { "params": [ "CliSSID" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "SSID" ], "type": "alias" }
      ],
      [
       { "params": [ "CliRSSI" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "RSSI" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wifi Channels",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 9, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Channel",
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "select count(distinct(\"CliMAC\")) FROM \"bsnMobileStationTable\" WHERE time > now() - 10m group by \"TCliSSID\"",
     "select": [
      [
       { "params": [ "hostname" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_wired", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Bandwidth / Wireless Devices",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_TCliMAC $col",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "TCliMAC" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "bsnMobileStationTable",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "CliBytesReceived" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "CliBytesSent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}