{
 "title": "WLC General Infos",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "type": "text", "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 }, "content": "# Cisco WLC general infos" },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "wlc-stats",
     "select": [
      [
       { "params": [ "wlc_Model" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "wlc-stats",
     "select": [
      [
       { "params": [ "wlc_Product_Version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "wlc-stats",
     "select": [
      [
       { "params": [ "wlc_OS" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "wlc-stats",
     "select": [
      [
       { "params": [ "wlc_CPU_Usage" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM free",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
   "format": "decmbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "wlc-stats",
     "select": [
      [
       { "params": [ "wlc_free_RAM" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1024" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total wireless clients",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "wlc-stats",
     "select": [
      [
       { "params": [ "wlc_total_clients" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wireless Access Points",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "APName" ], "type": "tag" }
     ],
     "measurement": "bsnAPTable",
     "select": [
      [
       { "params": [ "APLocation" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Location" ], "type": "alias" }
      ],
      [
       { "params": [ "radio24Users" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "2.4 GHz Users" ], "type": "alias" }
      ],
      [
       { "params": [ "radio5Users" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "5 GHz Users" ], "type": "alias" }
      ],
      [
       { "params": [ "24GUtil" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Usage" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wireless SSID",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "SSID" ], "type": "tag" }
     ],
     "measurement": "bsnDot11EssTable",
     "select": [
      [
       {
        "params": [
         "bsnDot11EssNumberOfMobileStations"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Clients" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}