# unbind crtl+b, use crtl+a
set -g mouse on
set -g prefix C-a
unbind C-b
bind C-a send-prefix
set -g status-bg cyan
set -g window-status-style bg=yellow
set -g window-status-current-style bg=red,fg=white
set-option -g set-clipboard on

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind '%'

# How to send a command to all panes in tmux
## PREFIX (Ctrl-A in our case) : setw synchronize-panes on
## clear history
