{
 "title": "RPC/SQL general stats",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "SISTEMA", "query": "influxdb" },
   { "name": "AGGR_INTERVAL", "query": "1m,3m,5m,10m,15m,30m,1h" },
   {
    "name": "AXT",
    "query": "SHOW TAG VALUES FROM \"ETW\" WITH KEY = \"AxInstance\""
   },
   {
    "name": "USER",
    "query": "SHOW TAG VALUES FROM \"ETW\" WITH KEY = \"AxUser\""
   },
   {
    "name": "HOSTNAME",
    "query": "SHOW TAG VALUES FROM \"ETW\" WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "RPC nestlevel0",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "RPC_nestlevel0_duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW_stats",
       "select": [
        [
         { "params": [ "RPC_nestlevel0_duration_sum" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      }
     ]
    },
    {
     "title": "count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "RPC_nestlevel0_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW_stats",
       "select": [
        [
         { "params": [ "RPC_nestlevel0_count_sum" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "RPC on SERVER",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "RPC_server_duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW_stats",
       "select": [
        [
         { "params": [ "RPC_server_duration_sum" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      }
     ]
    },
    {
     "title": "count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "query": "SELECT mean(\"SqlStmtCount_Total\") FROM \"SQL\" WHERE $timeFilter GROUP BY time($interval), \"AxUser\", \"AxSession\", \"AxInstance\", \"AxConDBSpid\" fill(null)",
       "select": [
        [
         { "params": [ "RPC_all_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW_stats",
       "query": "SELECT mean(\"SqlStmtCount_Total\") FROM \"SQL\" WHERE $timeFilter GROUP BY time($interval), \"AxUser\", \"AxSession\", \"AxInstance\", \"AxConDBSpid\" fill(null)",
       "select": [
        [
         { "params": [ "RPC_all_count_sum" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "RPC time details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "client duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "RPC_client_duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW_stats",
       "select": [
        [
         { "params": [ "RPC_client_duration_max" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      }
     ]
    },
    {
     "title": "whole duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "RPC_whole_duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW_stats",
       "select": [
        [
         { "params": [ "RPC_whole_duration_max" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "SQL BUSINESS DB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "SQL_stmt_duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW_stats",
       "select": [
        [
         { "params": [ "SQL_stmt_duration_sum" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      }
     ]
    },
    {
     "title": "count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "query": "SELECT sum(\"stmt_count\") FROM \"SQL\" WHERE \"AxUser\" =~ /^$USER$/ AND \"AxSession\" =~ /^$SESSION$/ AND \"AxInstance\" =~ /^$AXINSTANCE$/ AND $timeFilter GROUP BY time(1m), \"AxSession\", \"AxUser\", \"AxInstance\"",
       "select": [
        [
         { "params": [ "SQL_stmt_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW_stats",
       "query": "SELECT sum(\"stmt_count\") FROM \"SQL\" WHERE \"AxUser\" =~ /^$USER$/ AND \"AxSession\" =~ /^$SESSION$/ AND \"AxInstance\" =~ /^$AXINSTANCE$/ AND $timeFilter GROUP BY time(1m), \"AxSession\", \"AxUser\", \"AxInstance\"",
       "select": [
        [
         { "params": [ "SQL_stmt_count_sum" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "SQL MODELSTORE DB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "query": "SELECT sum(\"SQL_modelstoredproc_duration\") FROM \"ETW\" WHERE \"AxInstance\" =~ /^$AXT$/ AND \"AxUser\" =~ /^$USER$/ AND \"AxSession\" =~ /^$SESSION$/ AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"AxInstance\", \"AxUser\", \"AxSession\"",
       "select": [
        [
         { "params": [ "SQL_modelstoredproc_duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW_stats",
       "query": "SELECT sum(\"SQL_modelstoredproc_duration\") FROM \"ETW\" WHERE \"AxInstance\" =~ /^$AXT$/ AND \"AxUser\" =~ /^$USER$/ AND \"AxSession\" =~ /^$SESSION$/ AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"AxInstance\", \"AxUser\", \"AxSession\"",
       "select": [
        [
         {
          "params": [
           "SQL_modelstoredproc_duration_sum"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      }
     ]
    },
    {
     "title": "count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "query": "SELECT mean(\"SqlStmtCount_Total\") FROM \"SQL\" WHERE $timeFilter GROUP BY time($interval), \"AxUser\", \"AxSession\", \"AxInstance\", \"AxConDBSpid\" fill(null)",
       "select": [
        [
         { "params": [ "SQL_modelstoredproc_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW_stats",
       "query": "SELECT mean(\"SqlStmtCount_Total\") FROM \"SQL\" WHERE $timeFilter GROUP BY time($interval), \"AxUser\", \"AxSession\", \"AxInstance\", \"AxConDBSpid\" fill(null)",
       "select": [
        [
         { "params": [ "SQL_modelstoredproc_count_max" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "SQL FETCHES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "FETCH_duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW_stats",
       "select": [
        [
         { "params": [ "FETCH_duration_sum" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      }
     ]
    },
    {
     "title": "count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "FETCH_fetches_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW_stats",
       "select": [
        [
         { "params": [ "FETCH_fetches_count_sum" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "BYTES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "BYTES SENT",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "RPC_bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW_stats",
       "select": [
        [
         { "params": [ "RPC_bytes_sent_sum" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      }
     ]
    },
    {
     "title": "BYTES RECV",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "RPC_bytes_recd" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" }
       ],
       "measurement": "ETW_stats",
       "select": [
        [
         { "params": [ "RPC_bytes_recd_sum" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}