{
 "title": "RPC/SQL detailed stats",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "SISTEMA", "query": "influxdb" },
   { "name": "AGGR_INTERVAL", "query": "1m,3m,5m,10m,15m,30m,1h" },
   {
    "name": "AXT",
    "query": "SHOW TAG VALUES FROM \"ETW\" WITH KEY = \"AxInstance\""
   },
   {
    "name": "USER",
    "query": "SHOW TAG VALUES FROM \"ETW\" WITH KEY = \"AxUser\""
   },
   {
    "name": "SESSION",
    "query": "SHOW TAG VALUES FROM \"ETW\" WITH KEY = \"AxSession\""
   },
   {
    "name": "HOSTNAME",
    "query": "SHOW TAG VALUES FROM \"ETW\" WITH KEY = \"host\""
   },
   {
    "name": "duration",
    "label": "DURATION",
    "query": "50ms, 100ms, 200ms, 500ms, 1sec, 2sec, over2sec, over10sec"
   }
  ]
 },
 "panels": [
  {
   "title": "RPC nestlevel0",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "RPC_nestlevel0_duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "RPC_nestlevel0_duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    },
    {
     "title": "count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "RPC_nestlevel0_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "RPC_nestlevel0_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "RPC HISTOGRAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC HIST 50ms",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ETW_hist_temp",
       "select": [
        [
         { "params": [ "RPC_50ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "RPC_50ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    },
    {
     "title": "RPC HIST [[duration]]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ETW_hist_temp",
       "query": "SELECT sum(\"RPC_[[duration]]\") FROM \"autogen\".\"ETW_hist_temp\" WHERE (\"AxInstance\" =~ /^$AXT$/ AND \"AxUser\" =~ /^$USER$/) AND \"AxSession\" =~ /^$SESSION$/ AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"AxInstance\", \"AxUser\", \"AxSession\" fill(null)",
       "select": [
        [
         { "params": [ "RPC_50ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ETW",
       "query": "SELECT sum(\"RPC_[[duration]]\") FROM \"etwrp\".\"ETW\" WHERE (\"AxInstance\" =~ /^$AXT$/ AND \"AxUser\" =~ /^$USER$/) AND \"AxSession\" =~ /^$SESSION$/ AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"AxInstance\", \"AxUser\", \"AxSession\" fill(null)",
       "select": [
        [
         { "params": [ "RPC_50ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    },
    {
     "title": "RPC HIST over 50ms",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" },
        { "params": [ "AxInstance" ], "type": "tag" }
       ],
       "measurement": "ETW_hist_temp",
       "select": [
        [
         { "params": [ "RPC_100ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "50-100ms" ], "type": "alias" }
        ],
        [
         { "params": [ "rpc_200ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "100-200ms" ], "type": "alias" }
        ],
        [
         { "params": [ "RPC_500ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "200-500ms" ], "type": "alias" }
        ],
        [
         { "params": [ "RPC_1sec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "500ms-1sec" ], "type": "alias" }
        ],
        [
         { "params": [ "RPC_10sec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "1-10sec" ], "type": "alias" }
        ],
        [
         { "params": [ "RPC_over10sec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "over10sec" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" },
        { "params": [ "AxInstance" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "RPC_100ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "50-100ms" ], "type": "alias" }
        ],
        [
         { "params": [ "rpc_200ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "100-200ms" ], "type": "alias" }
        ],
        [
         { "params": [ "RPC_500ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "200-500ms" ], "type": "alias" }
        ],
        [
         { "params": [ "RPC_1sec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "500ms-1sec" ], "type": "alias" }
        ],
        [
         { "params": [ "RPC_10sec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "1-10sec" ], "type": "alias" }
        ],
        [
         { "params": [ "RPC_over10sec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "over10sec" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "RPC on SERVER",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "RPC_server_duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "RPC_server_duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    },
    {
     "title": "count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "query": "SELECT mean(\"SqlStmtCount_Total\") FROM \"SQL\" WHERE $timeFilter GROUP BY time($interval), \"AxUser\", \"AxSession\", \"AxInstance\", \"AxConDBSpid\" fill(null)",
       "select": [
        [
         { "params": [ "RPC_all_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "query": "SELECT mean(\"SqlStmtCount_Total\") FROM \"SQL\" WHERE $timeFilter GROUP BY time($interval), \"AxUser\", \"AxSession\", \"AxInstance\", \"AxConDBSpid\" fill(null)",
       "select": [
        [
         { "params": [ "RPC_all_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "RPC time details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "client duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "RPC_client_duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "RPC_client_duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    },
    {
     "title": "whole duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "RPC_whole_duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "RPC_whole_duration" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "SQL BUSINESS DB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "SQL_stmt_duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "SQL_stmt_duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    },
    {
     "title": "count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "query": "SELECT sum(\"stmt_count\") FROM \"SQL\" WHERE \"AxUser\" =~ /^$USER$/ AND \"AxSession\" =~ /^$SESSION$/ AND \"AxInstance\" =~ /^$AXINSTANCE$/ AND $timeFilter GROUP BY time(1m), \"AxSession\", \"AxUser\", \"AxInstance\"",
       "select": [
        [
         { "params": [ "SQL_stmt_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "query": "SELECT sum(\"stmt_count\") FROM \"SQL\" WHERE \"AxUser\" =~ /^$USER$/ AND \"AxSession\" =~ /^$SESSION$/ AND \"AxInstance\" =~ /^$AXINSTANCE$/ AND $timeFilter GROUP BY time(1m), \"AxSession\", \"AxUser\", \"AxInstance\"",
       "select": [
        [
         { "params": [ "SQL_stmt_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "SQL BUSINESS DB HISTOGRAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "under 50 ms",
     "type": "graph",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW_hist_temp",
       "query": "SELECT sum(\"SQL_Stmt\") FROM \"ETW_hist\" WHERE \"AxInstance\" =~ /^$AXT$/ AND \"AxUser\" =~ /^$USER$/ AND \"AxSession\" =~ /^$SESSION$/ AND \"Hthreshold\" = '50ms' AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"AxInstance\", \"AxUser\", \"AxSession\", \"Hthreshold\"",
       "select": [
        [
         { "params": [ "SQL_Stmt_50ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "<50ms" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "query": "SELECT sum(\"SQL_Stmt\") FROM \"ETW_hist\" WHERE \"AxInstance\" =~ /^$AXT$/ AND \"AxUser\" =~ /^$USER$/ AND \"AxSession\" =~ /^$SESSION$/ AND \"Hthreshold\" = '50ms' AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"AxInstance\", \"AxUser\", \"AxSession\", \"Hthreshold\"",
       "select": [
        [
         { "params": [ "SQL_Stmt_50ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "<50ms" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    },
    {
     "title": "[[duration]]",
     "type": "graph",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW_hist_temp",
       "query": "SELECT sum(\"SQL_Stmt_[[duration]]\") AS \"[[duration]]\" FROM \"autogen\".\"ETW_hist_temp\" WHERE (\"AxInstance\" =~ /^$AXT$/ AND \"AxUser\" =~ /^$USER$/) AND \"AxSession\" =~ /^$SESSION$/ AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"AxInstance\", \"AxUser\", \"AxSession\"",
       "select": [
        [
         { "params": [ "SQL_Stmt_50ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "<50ms" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "query": "SELECT sum(\"SQL_Stmt_[[duration]]\") AS \"[[duration]]\" FROM \"etwrp\".\"ETW\" WHERE (\"AxInstance\" =~ /^$AXT$/ AND \"AxUser\" =~ /^$USER$/) AND \"AxSession\" =~ /^$SESSION$/ AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"AxInstance\", \"AxUser\", \"AxSession\"",
       "select": [
        [
         { "params": [ "SQL_Stmt_50ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "<50ms" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    },
    {
     "title": "over 50 ms",
     "type": "graph",
     "gridPos": { "h": 13, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW_hist_temp",
       "query": "SELECT sum(\"SQL_Stmt\") FROM \"ETW_hist\" WHERE \"AxInstance\" =~ /^$AXT$/ AND \"AxUser\" =~ /^$USER$/ AND \"AxSession\" =~ /^$SESSION$/ AND \"Hthreshold\" = '50ms' AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"AxInstance\", \"AxUser\", \"AxSession\", \"Hthreshold\"",
       "select": [
        [
         { "params": [ "SQL_Stmt_100ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "50-100ms" ], "type": "alias" }
        ],
        [
         { "params": [ "SQL_Stmt_200ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "100-200ms" ], "type": "alias" }
        ],
        [
         { "params": [ "SQL_Stmt_500ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "200-500ms" ], "type": "alias" }
        ],
        [
         { "params": [ "SQL_Stmt_1sec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "500ms-1sec" ], "type": "alias" }
        ],
        [
         { "params": [ "SQL_Stmt_2sec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "1-2sec" ], "type": "alias" }
        ],
        [
         { "params": [ "SQL_Stmt_over2sec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "over2sec" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "query": "SELECT sum(\"SQL_Stmt\") FROM \"ETW_hist\" WHERE \"AxInstance\" =~ /^$AXT$/ AND \"AxUser\" =~ /^$USER$/ AND \"AxSession\" =~ /^$SESSION$/ AND \"Hthreshold\" = '50ms' AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"AxInstance\", \"AxUser\", \"AxSession\", \"Hthreshold\"",
       "select": [
        [
         { "params": [ "SQL_Stmt_100ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "50-100ms" ], "type": "alias" }
        ],
        [
         { "params": [ "SQL_Stmt_200ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "100-200ms" ], "type": "alias" }
        ],
        [
         { "params": [ "SQL_Stmt_500ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "200-500ms" ], "type": "alias" }
        ],
        [
         { "params": [ "SQL_Stmt_1sec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "500ms-1sec" ], "type": "alias" }
        ],
        [
         { "params": [ "SQL_Stmt_2sec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "1-2sec" ], "type": "alias" }
        ],
        [
         { "params": [ "SQL_Stmt_over2sec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "over2sec" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "SQL MODELSTORE DB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "query": "SELECT sum(\"SQL_modelstoredproc_duration\") FROM \"ETW\" WHERE \"AxInstance\" =~ /^$AXT$/ AND \"AxUser\" =~ /^$USER$/ AND \"AxSession\" =~ /^$SESSION$/ AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"AxInstance\", \"AxUser\", \"AxSession\"",
       "select": [
        [
         { "params": [ "SQL_modelstoredproc_duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "query": "SELECT sum(\"SQL_modelstoredproc_duration\") FROM \"ETW\" WHERE \"AxInstance\" =~ /^$AXT$/ AND \"AxUser\" =~ /^$USER$/ AND \"AxSession\" =~ /^$SESSION$/ AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"AxInstance\", \"AxUser\", \"AxSession\"",
       "select": [
        [
         { "params": [ "SQL_modelstoredproc_duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    },
    {
     "title": "count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "query": "SELECT mean(\"SqlStmtCount_Total\") FROM \"SQL\" WHERE $timeFilter GROUP BY time($interval), \"AxUser\", \"AxSession\", \"AxInstance\", \"AxConDBSpid\" fill(null)",
       "select": [
        [
         { "params": [ "SQL_modelstoredproc_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "query": "SELECT mean(\"SqlStmtCount_Total\") FROM \"SQL\" WHERE $timeFilter GROUP BY time($interval), \"AxUser\", \"AxSession\", \"AxInstance\", \"AxConDBSpid\" fill(null)",
       "select": [
        [
         { "params": [ "SQL_modelstoredproc_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "SQL MODELSTORE DB HISTOGRAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "under 50 ms",
     "type": "graph",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW_hist_temp",
       "query": "SELECT sum(\"SQL_Stmt\") FROM \"ETW_hist\" WHERE \"AxInstance\" =~ /^$AXT$/ AND \"AxUser\" =~ /^$USER$/ AND \"AxSession\" =~ /^$SESSION$/ AND \"Hthreshold\" = '50ms' AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"AxInstance\", \"AxUser\", \"AxSession\", \"Hthreshold\"",
       "select": [
        [
         { "params": [ "SQL_ModelStored_50ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "query": "SELECT sum(\"SQL_Stmt\") FROM \"ETW_hist\" WHERE \"AxInstance\" =~ /^$AXT$/ AND \"AxUser\" =~ /^$USER$/ AND \"AxSession\" =~ /^$SESSION$/ AND \"Hthreshold\" = '50ms' AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"AxInstance\", \"AxUser\", \"AxSession\", \"Hthreshold\"",
       "select": [
        [
         { "params": [ "SQL_ModelStored_50ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    },
    {
     "title": "[[duration]]",
     "type": "graph",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW_hist_temp",
       "query": "SELECT sum(\"SQL_ModelStored_[[duration]]\") FROM \"autogen\".\"ETW_hist_temp\" WHERE (\"AxInstance\" =~ /^$AXT$/ AND \"AxUser\" =~ /^$USER$/) AND \"AxSession\" =~ /^$SESSION$/ AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"AxInstance\", \"AxUser\", \"AxSession\"",
       "select": [
        [
         { "params": [ "SQL_ModelStored_50ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "query": "SELECT sum(\"SQL_ModelStored_[[duration]]\") FROM \"etwrp\".\"ETW\" WHERE (\"AxInstance\" =~ /^$AXT$/ AND \"AxUser\" =~ /^$USER$/) AND \"AxSession\" =~ /^$SESSION$/ AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"AxInstance\", \"AxUser\", \"AxSession\"",
       "select": [
        [
         { "params": [ "SQL_ModelStored_50ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    },
    {
     "title": "over 50 ms",
     "type": "graph",
     "gridPos": { "h": 13, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW_hist_temp",
       "query": "SELECT sum(\"SQL_Stmt\") FROM \"ETW_hist\" WHERE \"AxInstance\" =~ /^$AXT$/ AND \"AxUser\" =~ /^$USER$/ AND \"AxSession\" =~ /^$SESSION$/ AND \"Hthreshold\" = '50ms' AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"AxInstance\", \"AxUser\", \"AxSession\", \"Hthreshold\"",
       "select": [
        [
         { "params": [ "SQL_ModelStored_100ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "50-100ms" ], "type": "alias" }
        ],
        [
         { "params": [ "SQL_ModelStored_200ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "100-200ms" ], "type": "alias" }
        ],
        [
         { "params": [ "SQL_ModelStored_500ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "200-500ms" ], "type": "alias" }
        ],
        [
         { "params": [ "SQL_ModelStored_1sec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "500ms-1sec" ], "type": "alias" }
        ],
        [
         { "params": [ "SQL_ModelStored_2sec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "1-2sec" ], "type": "alias" }
        ],
        [
         { "params": [ "SQL_ModelStored_over2sec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "over2sec" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "query": "SELECT sum(\"SQL_Stmt\") FROM \"ETW_hist\" WHERE \"AxInstance\" =~ /^$AXT$/ AND \"AxUser\" =~ /^$USER$/ AND \"AxSession\" =~ /^$SESSION$/ AND \"Hthreshold\" = '50ms' AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"AxInstance\", \"AxUser\", \"AxSession\", \"Hthreshold\"",
       "select": [
        [
         { "params": [ "SQL_ModelStored_100ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "50-100ms" ], "type": "alias" }
        ],
        [
         { "params": [ "SQL_ModelStored_200ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "100-200ms" ], "type": "alias" }
        ],
        [
         { "params": [ "SQL_ModelStored_500ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "200-500ms" ], "type": "alias" }
        ],
        [
         { "params": [ "SQL_ModelStored_1sec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "500ms-1sec" ], "type": "alias" }
        ],
        [
         { "params": [ "SQL_ModelStored_2sec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "1-2sec" ], "type": "alias" }
        ],
        [
         { "params": [ "SQL_ModelStored_over2sec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "over2sec" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "SQL FETCHES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "FETCH_duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "FETCH_duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    },
    {
     "title": "count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "FETCH_fetches_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "FETCH_fetches_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    },
    {
     "title": "cumulative duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "FETCH_cumu_duration" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "FETCH_cumu_duration" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    },
    {
     "title": "rows count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "FETCH_rows_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "FETCH_rows_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "SQL FETCHES HISTOGRAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "under 50 ms",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW_hist_temp",
       "select": [
        [
         { "params": [ "FETCH_50ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "FETCH_50ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    },
    {
     "title": "[[duration]]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW_hist_temp",
       "query": "SELECT sum(\"FETCH_[[duration]]\") FROM \"autogen\".\"ETW_hist_temp\" WHERE (\"AxInstance\" =~ /^$AXT$/ AND \"AxUser\" =~ /^$USER$/) AND \"AxSession\" =~ /^$SESSION$/ AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"AxInstance\", \"AxUser\", \"AxSession\"",
       "select": [
        [
         { "params": [ "FETCH_50ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "query": "SELECT sum(\"FETCH_[[duration]]\") FROM \"etwrp\".\"ETW\" WHERE (\"AxInstance\" =~ /^$AXT$/ AND \"AxUser\" =~ /^$USER$/) AND \"AxSession\" =~ /^$SESSION$/ AND $timeFilter GROUP BY time($AGGR_INTERVAL), \"AxInstance\", \"AxUser\", \"AxSession\"",
       "select": [
        [
         { "params": [ "FETCH_50ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    },
    {
     "title": "over 50 ms",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW_hist_temp",
       "select": [
        [
         { "params": [ "FETCH_100ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "50-100ms" ], "type": "alias" }
        ],
        [
         { "params": [ "FETCH_200ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "100-200ms" ], "type": "alias" }
        ],
        [
         { "params": [ "FETCH_500ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "200-500ms" ], "type": "alias" }
        ],
        [
         { "params": [ "FETCH_1sec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "500ms-1sec" ], "type": "alias" }
        ],
        [
         { "params": [ "FETCH_2sec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "1-2sec" ], "type": "alias" }
        ],
        [
         { "params": [ "FETCH_over2sec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "over2sec" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "FETCH_100ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "50-100ms" ], "type": "alias" }
        ],
        [
         { "params": [ "FETCH_200ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "100-200ms" ], "type": "alias" }
        ],
        [
         { "params": [ "FETCH_500ms" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "200-500ms" ], "type": "alias" }
        ],
        [
         { "params": [ "FETCH_1sec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "500ms-1sec" ], "type": "alias" }
        ],
        [
         { "params": [ "FETCH_2sec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "1-2sec" ], "type": "alias" }
        ],
        [
         { "params": [ "FETCH_over2sec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "over2sec" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "BYTES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "BYTES SENT",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "RPC_bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "RPC_bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    },
    {
     "title": "BYTES RECV",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "RPC_bytes_recd" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$AGGR_INTERVAL" ], "type": "time" },
        { "params": [ "AxInstance" ], "type": "tag" },
        { "params": [ "AxUser" ], "type": "tag" },
        { "params": [ "AxSession" ], "type": "tag" }
       ],
       "measurement": "ETW",
       "select": [
        [
         { "params": [ "RPC_bytes_recd" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "AxInstance", "operator": "=~", "value": "/^$AXT$/" },
        { "condition": "AND", "key": "AxUser", "operator": "=~", "value": "/^$USER$/" },
        { "condition": "AND", "key": "AxSession", "operator": "=~", "value": "/^$SESSION$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}