# neteye test instance should point to internal pulp repo
#
---
- hosts: localhost
  any_errors_fatal: true
  gather_facts: false

  vars:
    path_dnf_mirror: "/etc/yum.repos.d/mirrors"

  #vars_files:
  #  - defaults/pulp_defaults.yml

  tasks:

  - name: prerequisites | get the list of repo files in /etc/yum.repos.d/
    find:
      paths: "{{ path_dnf_mirror }}"
      patterns: "*.mirror"
    register: repofiles

  - name: prerequisites | replace strings in files found
    replace:
      dest: "{{ item.path }}"
      backup: yes
      regexp: 'https://repo\.wuerth-phoenix\.com'
      replace: 'http://pulp2internal.wp.lan'
    loop: "{{ repofiles.files }}"
